name: PR Test
 
on:
  pull_request:
    branches: [ master ] # master branch에 PR을 보낼 때 실행
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: install dependency packages
        run: pip install -r requirements.txt
  
      # test를 실행한다
      - name: Test run
        run: bash ./run_unittest_linux.sh